title: "MPC wiki"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/MPCA_logo_white_h.png"